### ISSUE TITLE
BUG: Copy Row (Insert) -- Not working from query results

### ISSUE THREAD

**Issue by gsigler** [beekeeper-studio/beekeeper-studio#1460]
**Describe the bug**
When I try to copy a row to insert from the query results page nothing gets copied to my clipboard. 

**To Reproduce**
1. Open new query page
2. Query for some data
3. Right click on row and select Copy Row (Insert) 
4. Nothing in clipboard

**Expected behavior**
I should get the same result I see when I do this from the view database view. 

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 3.4.10

**Additional context**
Anything else you think might be helpful

**Comment by samputer** [comment]
+1 - seeing this also

**Comment by lanzoninicola** [comment]
I'm interested in contributing to resolve it. I'll keep working on trying to find a solution and will keep you updated on my progress. Thank you!

**Comment by lanzoninicola** [comment]
After reviewing the issue, it appears that the "Copy Row (Insert)" function on the query results page is not working. Upon examining the code, I can confirm that it is not functioning as intended.

However, I also question the usefulness of this function in the context of query results. In scenarios where a query involves multiple joins or complex subqueries, it may not be clear which insert query the software should propose. Therefore, in my opinion, it may be more appropriate to remove this option altogether.

@gsigler @samputer If there is something I am missing or if you have a different opinion, please let me know. Nonetheless, I believe it is reasonable to question the usefulness of this function in the given context.

I think it is appropriate to ask @rathboma's opinion on how best to proceed with this issue.

**Comment by shiftlabs1** [comment]
@lanzoninicola  This is a useful feature. On a day-to-day basis we do not only copy the data to excel or CSV. some are static data that need to be immediately applied as is in the same DB in another environment. Copying as Insert is the way that is done and this is a feature you find in use on other IDEs like DBeaver. Also, the fact that its one of the menu item highlights its usefulness to the original product design. It should be fixed. 
It is not even a feature ask, but one to fix an issue on a supposed existing feature.

**Comment by lanzoninicola** [comment]
@shiftlabs1 I would like to clarify that I'm not part of the maintenance team, and I apologize for not mentioning this in my previous message. As a developer who is interested in contributing to the project, my comments were based on my personal opinion and may not reflect the views of the maintainers. 

Additionally, I have not used DBeaver before and am not familiar with how their feature works. 

However, I would be interested in taking a look at it and learning more about it.

**Comment by M3psipax** [comment]
I wanna bump this issue. Is there any ETA on it? Any way I can help?

**Comment by carlosrovai** [comment]
still having the same issue

**Comment by not-night-but** [comment]
Looks like this is still happening in certain cases. Wasn't able to reproduce in sqlite, but I get the issue in psql: 

![Image](https://github.com/user-attachments/assets/a16d6e2d-70dc-4995-948b-f24a39d0d91d)
