### ISSUE TITLE
BUG: Error when starting the program

### ISSUE THREAD

**Issue by frxndev** [beekeeper-studio/beekeeper-studio#2769]
**Describe the bug**
When I try to open the beekeeper program it simply does not start, it does not load any view, however in the task manager it is seen to be running and multiple executions are visible.

**To Reproduce**
1. Install the beta version v5.1.0-beta.10
2. Open the application
3. And you will see that the program does not appear in view but in the task manager.

**Expected behavior**
It should open the sale of the program normally and this is not happening.

**Screenshots / Gifs**

![Image](https://github.com/user-attachments/assets/830d5307-2202-4234-b09a-f74596e8b2ed)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 5.1.0-beta.10

**Additional context**
I downloaded the stable version of the program and it does not let me save any connection and the existing ones do not appear.

![Image](https://github.com/user-attachments/assets/32c89807-3b64-4cc8-b58a-0482afd2f2b7)

**Comment by not-night-but** [comment]
@frxndev to fix being able to open the app on the stable version, copy your `app.db` file to a different directory or rename it (`%APPDATA%\beekeeper-studio\app.db`). That will force the app to regenerate the local db and allow you to use it again. You'll have to reimport your connections (I'd connect to the old db, export your `saved_connections` to a sql insert, and make sure you rename the `url` column to `uri`)

In terms of what's happening in the beta version, no window appears at all? Are there any logs in `%APPDATA%\beekeeper-studio\logs\` might clue us in to what's going on? There should be a `main.log`, `renderer.log`, and a `utility.log`.

**Comment by frxndev** [comment]
Yes, I located the logs, but there is only main.log, utility.log, which I attach both.

[main.log](https://github.com/user-attachments/files/18804640/main.log)
[utility.log](https://github.com/user-attachments/files/18804641/utility.log)

**Comment by not-night-but** [comment]
Okay so it looks like the renderer isn't actually starting, and the utility process is starting, crashing, restarting and just getting stuck in that loop. So there's definitely something wrong. I'll see if I can reproduce it on linux

**Comment by Stef-Verniers** [comment]
@not-night-but Can you suggest me how I could fix the issue on Mac? Or is it an actual bug that needs a fix?

**Comment by not-night-but** [comment]
This was fixed in beta 11

**Comment by rujorgensen** [comment]
@not-night-but  can you provide some additional info about the cause of the problem? I'm experiencing this exact issue now, with the current version I downloaded from the download page (v. 5.3.6). Both normal and portable.

**Comment by CycomMEwald** [comment]
Same here, 5.3.6, it's rapidly restarting and filling `utility.log` with the same few messages indicating that it's loading its configuration, finished loading the configuration and then appears to start over.

**Comment by ferpujol** [comment]
Hello. I had installed Beekeper Studio until I had to factory reset my PC and when reinstalling BS again, is not opening. I deleted the whole app data so it can be recreated but still no luck. What could be wrong?

**Comment by not-night-but** [comment]
@ferpujol I believe you may need to install the MSVC redistributables for your system: https://docs.beekeeperstudio.io/support/troubleshooting/#the-app-is-stuck-running-in-the-background
