### ISSUE TITLE
BUG: Old saved queries cannot be saved again

### ISSUE THREAD

**Issue by KuechlerO** [beekeeper-studio/beekeeper-studio#969]
**Describe the bug**
I just downloaded an update of Beekeeper Studio (Version 3.0.7).
But now I encounter a bug, where I cannot anymore manipulate my old saved queries and safe them afterwards.

**To Reproduce**
1. Have old queries and safe them before updating to new Beekeeper Studio version (I don't know my previous version...)
2. Update Beekeeper -> Using Beekeeper's own download and restart dialog pop-ups
3. Open Connection & access old queries again
4. Try to save queries -> Error: "You need both a title, and some query text"

**Expected behavior**
First of all, the queries should not be displayed as manipulated (white dot appears in tab-header), when I just open the old query. Furthermore saving should be no problem, when the old query already has query-text and query-title.

**Screenshots / Gifs**
<img width="1193" alt="Beekeeper_Bug" src="https://user-images.githubusercontent.com/65129900/148687140-b3dbaa4a-394b-4d6b-abbf-494e3113ea50.png">

**Version Information (please complete the following information):**
 - OS: MacOS Big Sur
 - App Version: Beekeeper Studio (Version 3.0.7).

**Additional context**
I use Beekeeper to handle my PostGre-SQL database.

**Comment by KuechlerO** [comment]
A workaround is to simply create new queries, copy your old query-code inside them, and then save them accordingly.

**Comment by rathboma** [comment]
Can you try restarting beekeeper and see if it works then? The sidebar looks like you're in some weird state I don't understand.

I'll try and replicate tomorrow. Sorry you hit this problem :-(

**Comment by KuechlerO** [comment]
> Can you try restarting beekeeper and see if it works then? The sidebar looks like you're in some weird state I don't understand.
> 
> I'll try and replicate tomorrow. Sorry you hit this problem :-(

Oh wow, that was a quick reply. Thx very much! Don't worry much, it's not such a big deal, I was just surprised and thought it's worth reporting.

No, restarting Beekeeper does not solve the problem.

Also I recognized, that sometimes (potentially when I first open an old query after the update) I get a dialog asking me to merge my query...
<img width="1195" alt="Bildschirmfoto 2022-01-09 um 16 06 11" src="https://user-images.githubusercontent.com/65129900/148688233-a784fc6a-440d-4b57-9da4-63d06e8841a4.png">

After merging that query, everything is fine and I can continue working on that query. 
However, this applies only to that specific query, and for the other queries I do not receive such an option.

Best regards and thx for your work!!! <3

**Comment by rathboma** [comment]
Can you open the dev console and see if there are any errors? Help - show dev console

**Comment by KuechlerO** [comment]
Yeah, I got a lot of warnings and one error. Here's a screenshot:
<img width="1049" alt="Bildschirmfoto 2022-01-09 um 19 03 07" src="https://user-images.githubusercontent.com/65129900/148694542-df4deff8-1be4-4968-ac74-4e3a61457d91.png">

**Comment by KuechlerO** [comment]
Ah, but that error appears when I try to delete the nameless query from my sidebar.

**Comment by rathboma** [comment]
Yes that nameless query is what is making me think something is up.

Is that there as soon as you open a connection? I can replicate the nameless query by closing a tab -- something I've just fixed, but it's not there when I open a connection for the first time. What about for you?

**Comment by KuechlerO** [comment]
Ah yes, I didn't notice, but it's true:

When I restart Beekeeper and open a connection, the nameless query is not listed on the left sidebar. 
However, as soon as I open one of my old saved queries and close it again (without saving, since the original bug is blocking me -> Beekeeper gives me a dialog: "Are you sure? You will lose unsaved changes." -> Press Ok), the nameless query appears again in the left sidebar.

Disconnecting and Reconnecting does not remove the nameless query from the sidebar. But killing and restarting Beekeeper removes it.

**Comment by rathboma** [comment]
Ok, if you kill and restart beekeeper - does everything work ok (saving and such) so long as you don't close a query tab?

**Comment by KuechlerO** [comment]
No for version 3.0.7, the at the very beginning described bug still persists.

I also now updated to version 3.0.9, which fixes the bug of creating a nameless query in the sidebar, but the previously mentioned bug also still exists here.

**Comment by KuechlerO** [comment]
Ok, apparently this problem also persists for creating new queries:
If I create a new query and save it, everything is fine at first. But when I close the query-tab and open it again, the same bug appears:
The query is marked as "edited" with the white dot, but when I try to save it I get the same error message as described before. (I attached a MOV-file demonstrating the issue. The quality is bad, but the problem should be visible.)

https://user-images.githubusercontent.com/65129900/149154496-202ee00a-0a49-4b94-9552-15a668b1ecd3.mov


Could you just tell me please, how I can reset the beekeeper-database, that saves all the queries and data, so that I can have a fresh start? I think that would be the fastest and safest workaround for me now, so that I can continue using the query-feature of Beekeeper.

**Comment by KuechlerO** [comment]
Ah, and when I have opened one of the queries, and I close an unnamed query-tab (e.g. Query #1), the other query-tab changes:

- white dot appears
- All query text gone
- blue text "This query has been updated by someone else."
- -> Offered opportunity to merge (merge doesn't seem to make a difference -> the original query is restored)

**Comment by rathboma** [comment]
Hey, I'm still unable to replicate this. If you want to kill the database and start fresh you can move the app.db file. There should be a Beekeeper folder somewhere in ~/Library/Application Support, you can check the path in the Beekeeper UI by looking at the sqlite path for Beekeeper's app.db.

Just move app.db to app.db.back and let me know if the problem persists?

**Comment by KuechlerO** [comment]
> Hey, I'm still unable to replicate this. If you want to kill the database and start fresh you can move the app.db file. There should be a Beekeeper folder somewhere in ~/Library/Application Support, you can check the path in the Beekeeper UI by looking at the sqlite path for Beekeeper's app.db.
> 
> Just move app.db to app.db.back and let me know if the problem persists?

Alright, I followed your steps and reset the beekeepers database. Now everything seems to work fine again.
Thx very much for your support @rathboma. Highly appreciated! ^^

P.S.:
If it helps you: I can send you my old beekeeper-DB-file. Maybe you can replicate the scenario with that.

**Comment by tushr7** [comment]
Hi @rathboma, I am having a similar issue. When trying the save changes in the existing query tab it does not let me save the updated query text. It displays error text as "you need both a title, query text". 

For the first time when a new tab is saved, it saves. But after making changes in this same tab - save does not work. 

**OS:** Parrot OS | Debian
**App Version:** 3.2.1
**DB:**  (PostgreSQL) 13.5 (Debian 13.5-0+deb11u1)

![image](https://user-images.githubusercontent.com/95033922/156874011-10e0fb01-6a73-49fe-b515-0b4d1f7d883a.png)
![BeekeeperUnableToSaveQueryTab](https://user-images.githubusercontent.com/95033922/156875113-f9b636aa-b8e6-4958-a7cd-e61db3f21360.gif)

let me know if you need more assistance to debug. Thanks

_Also to notice that there is no scroll bar in the preview tab. Refer to attachments._

**Comment by canercetin-randomguy** [comment]
bump, same issue persists

**Comment by lukcaz** [comment]
The same problem keeps happening.
I really wanted to use beekeeper as the main client, but every time I reopen a project this error happens with previously saved queries. They already open with an error and do not allow saving, so I need to create a new query and name it. Very annoying.

**Comment by rathboma** [comment]
We've found this bug I think! Fix coming in a patch release

**Comment by mmuurr** [comment]
I've just started using Beekeeper and immediately ran into this issue; came to this GH Issue because I wasn't sure if this was somehow 'expected' behavior. I'm on v4.1.13; is this due to be fixed?

**Comment by rathboma** [comment]
@mmuurr If this happens again can you check the dev console (help -> show developer tools) to see if there are any errors?

We don't have any ability to reproduce this!

**Comment by tantweiler** [comment]
I do have the same issues as the people already explained here. When open a saved query and add content I get the error:

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/48676838/3490b234-fe98-4b3b-bd6b-3b05081e0d5f)

And the dev console shows the following errors:

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/48676838/2be9a0a7-2629-4ca6-a3fb-10c84e968121)
